version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    steps:
      - checkout
      - restore_cache:
          key: aghome-node-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: aghome-node-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
